services:
  boardgame.warofthering.dice.api:
    image: boardgame.warofthering.dice.api
    build:
      context: .
      dockerfile: BoardGame.WarOfTheRing.Dice/BoardGame.WarOfTheRing.Dice.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    ports:
      - 5111:8080
    networks:
      - backend
  
  boardgame.warofthering.politicaltrack.api:
    image: boardgame.warofthering.politicaltrack.api
    build:
      context: .
      dockerfile: BoardGame.WarOfTheRing.PoliticalTrack/BoardGame.WarOfTheRing.PoliticalTrack.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    ports:
      - 5145:8080
    networks:
      - backend
      
  boardgame.warofthering.fellowships.api:
    image: boardgame.warofthering.fellowships.api
    build:
      context: .
      dockerfile: BoardGame.WarOfTheRing.Fellowships/BoardGame.WarOfTheRing.Fellowships.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    ports:
      - 5280:8080
    networks:
      - backend
        
  db:
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - ~/apps/postgres-warofthering:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=aydin
    networks:
      - backend
    
  mountebank:
    container_name: mountebank
    image: bbyars/mountebank:latest
    volumes:
      - ./imposters:/imposters
    ports:
      - 2525:2525
      - 8090:8090
      - 8091:8091
    networks:
      - backend
    command: --configfile /imposters/imposters.ejs --allowInjection
    
  seq:
    image: datalust/seq:latest
    volumes:
      - ~/apps/seq-warofthering:/data
    restart: unless-stopped
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
  
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - "./BoardGame.WarOfTheRing.Gateway:/etc/krakend"
    ports:
      - "8080:8080"
    networks:
      - backend
    command: [ "run", "-dc", "krakend.json" ]
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/apps/rabbitmq-warofthering/data/:/var/lib/rabbitmq/
        - ~/apps/rabbitmq-warofthering/log/:/var/log/rabbitmq
    networks:
        - backend
  
networks:
  backend:
    
