services:
  boardgame.warofthering.dice.api:
    image: boardgame.warofthering.dice.api
    build:
      context: .
      dockerfile: BoardGame.WarOfTheRing.Dice.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
